# Generated by Django 3.2.2 on 2021-05-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inlineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('registry', models.CharField(max_length=256)),
                ('ship_class', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('captain', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inlineapp.officer')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlineapp.rank'),
        ),
        migrations.AddField(
            model_name='officer',
            name='ship_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inlineapp.ship'),
        ),
    ]
